import { readFileSync, writeFileSync } from 'fs';
import path from 'path';
import Papa from 'papaparse';

const out = path.resolve('build/extracted/ams2');
const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '');
const read = <T>(file: string) => Papa.parse<T>(readFileSync(file, 'utf8'), { header: true, skipEmptyLines: true }).data;
const pick = (row: Record<string, string>, fields: string[]) => Object.fromEntries(fields.map(field => [field, row[field] ?? '']));
const safeJson = (value: unknown) => JSON.stringify(value).replace(/</g, '\\u003c');

function main() {
  const appCars = read<Record<string, string>>('src/app/data/cars.csv');
  const gameCars = read<Record<string, string>>(path.join(out, 'bootflow_vehicle_details.csv'));
  const appTracks = read<Record<string, string>>('src/app/data/tracks.csv');
  const gameTracks = read<Record<string, string>>(path.join(out, 'bootflow_track_details.csv'));
  const carFields = ['Name', 'Vehicle Name', 'VehicleManufacturer', 'VehicleModel', 'Vehicle Year', 'Vehicle Class', 'Vehicle Group', 'Vehicle Shape', 'Vehicle Physics Model', 'DLC ID', 'Country'];
  const trackFields = ['Name', 'TrackName', 'ShortTrackName', 'Year', 'Length', 'Location', 'Country', 'Track Type', 'Track Group', 'Track_Variation', 'Class', 'DLC ID'];
  const carByName = new Map(gameCars.map(row => [norm(row['Vehicle Name']), pick(row, carFields)]));
  const trackByName = new Map(gameTracks.map(row => [norm(row.TrackName), pick(row, trackFields)]));
  const data = {
    cars: appCars.map(app => ({ app, game: carByName.get(norm(app.car)) ?? null })),
    tracks: appTracks.map(app => ({ app: { name: app.name, configuration: app.configuration }, game: trackByName.get(norm(app.name)) ?? null })),
    gameCars: gameCars.map(game => ({ app: appCars.find(app => norm(app.car) === norm(game['Vehicle Name'])) ?? null, game: pick(game, carFields) })),
    gameTracks: gameTracks.map(game => ({ app: appTracks.find(app => norm(app.name) === norm(game.TrackName)) ?? null, game: pick(game, trackFields) })),
  };
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AMS2 App vs Game Data</title><style>
:root{--ink:#18232c;--muted:#68737d;--line:#d7dfe3;--paper:#fff;--accent:#a7442e}*{box-sizing:border-box}body{margin:0;background:linear-gradient(135deg,#edf2f2,#f8f4ed);color:var(--ink);font:14px/1.45 Georgia,serif}main{max-width:1500px;margin:auto;padding:42px 28px 70px}h1{font-size:clamp(32px,5vw,58px);line-height:1;margin:0 0 10px;letter-spacing:-.04em}h2{margin:32px 0 12px}.lede{max-width:800px;font-size:16px;color:var(--muted)}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:28px 0}.card,.panel{background:var(--paper);border:1px solid var(--line);border-radius:12px}.card{padding:17px}.card strong{display:block;font-size:28px}.card span{color:var(--muted)}.tabs{display:flex;gap:8px;margin:28px 0 12px}button{border:1px solid var(--line);border-radius:999px;background:#fff;padding:9px 17px;cursor:pointer;font:600 14px Georgia,serif}button.active{background:var(--ink);color:#fff}.toolbar{display:flex;gap:12px;margin:12px 0}input,select{border:1px solid var(--line);border-radius:8px;padding:10px;background:#fff;font:14px Georgia,serif}input{flex:1}.panel{overflow:hidden}.table-wrap{overflow:auto;max-height:680px}table{border-collapse:collapse;width:100%;min-width:1000px}th,td{border-bottom:1px solid var(--line);padding:9px 11px;text-align:left;vertical-align:top}th{position:sticky;top:0;background:#e8eef0;text-transform:uppercase;font-size:11px;letter-spacing:.06em}td:first-child{font-weight:bold;white-space:nowrap}.game{color:#205f45}.missing{color:var(--accent);font-weight:bold}.note{background:#fff8e8;border-left:4px solid #d19a35;padding:12px 15px;color:#604b22}@media(max-width:700px){main{padding:28px 14px}.cards{grid-template-columns:repeat(2,1fr)}.toolbar{flex-wrap:wrap}}
</style></head><body><main><h1>AMS2 data, side by side</h1><p class="lede">Current career-app CSVs compared with metadata extracted from <code>Pakfiles/BOOTFLOW.bff</code>. Game values are source data; app values are editorial and are not assumed equivalent.</p><div class="cards" id="cards"></div><div class="note">Matching uses normalized display names. A missing match means names differ or the app row is editorial; it does not mean the game asset is absent.</div><div class="tabs"><button class="active" data-tab="cars">Vehicles</button><button data-tab="tracks">Tracks</button></div><section id="cars"><h2>Vehicles</h2><div class="toolbar"><input id="carSearch" placeholder="Search app or game vehicle name"><select id="carMode"><option value="app">App rows</option><option value="game">All extracted game rows</option></select></div><div class="panel"><div class="table-wrap"><table id="carTable"></table></div></div></section><section id="tracks" hidden><h2>Tracks</h2><div class="toolbar"><input id="trackSearch" placeholder="Search app or game track name"><select id="trackMode"><option value="app">App rows</option><option value="game">All extracted game rows</option></select></div><div class="panel"><div class="table-wrap"><table id="trackTable"></table></div></div></section></main><script>
const DATA=${safeJson(data)};const carCols=[['car','App name'],['class','App class'],['discipline','App discipline'],['year','App year'],['Vehicle Name','Game name'],['Vehicle Class','Game class'],['Vehicle Group','Game group'],['Vehicle Year','Game year'],['VehicleManufacturer','Manufacturer'],['Name','Asset id']];const trackCols=[['name','App name'],['configuration','App config'],['TrackName','Game name'],['Track_Variation','Game variation'],['Year','Game year'],['Location','Location'],['Country','Country'],['Track Type','Type'],['Track Group','Group'],['Class','Game class'],['Name','Asset id']];const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));function render(kind){const car=kind==='car',p=car?'car':'track',mode=document.getElementById(p+'Mode').value,q=document.getElementById(p+'Search').value.toLowerCase(),src=mode==='app'?(car?DATA.cars:DATA.tracks):(car?DATA.gameCars:DATA.gameTracks),cols=car?carCols:trackCols,rows=src.filter(x=>JSON.stringify(x).toLowerCase().includes(q));document.getElementById(p+'Table').innerHTML='<thead><tr>'+cols.map(x=>'<th>'+x[1]+'</th>').join('')+'</tr></thead><tbody>'+rows.map(x=>'<tr>'+cols.map(([key])=>{const v=mode==='app'?x.app?.[key]:x.game?.[key],missing=mode==='app'&&key===(car?'car':'name')&&!x.game;return '<td class="'+(missing?'missing ':'')+(mode==='game'?'game':'')+'">'+esc(v||(missing?'No display-name match':'—'))+'</td>'}).join('')+'</tr>').join('')+'</tbody>'}const cm=DATA.cars.filter(x=>x.game).length,tm=DATA.tracks.filter(x=>x.game).length;document.getElementById('cards').innerHTML=[['App vehicles',DATA.cars.length],['Game vehicles',DATA.gameCars.length],['Vehicle matches',cm+'/'+DATA.cars.length],['Track matches',tm+'/'+DATA.tracks.length]].map(x=>'<div class="card"><strong>'+x[1]+'</strong><span>'+x[0]+'</span></div>').join('');document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('section').forEach(x=>x.hidden=x.id!==b.dataset.tab)});['carSearch','carMode','trackSearch','trackMode'].forEach(id=>document.getElementById(id).oninput=()=>render(id.startsWith('car')?'car':'track'));render('car');render('track');</script></body></html>`;
  writeFileSync(path.resolve('build/extracted/ams2/data-comparison.html'), html);
  console.log(path.resolve('build/extracted/ams2/data-comparison.html'));
}

if (require.main === module) main();
